import Navbar from "@/app/components/Navbar";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import AuthProvider from "@/utils/SessionProvider"; // Use your custom provider

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "EarlyEdge",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-gray-100`}>
        <AuthProvider> {/* Use your custom AuthProvider */}
          <div className="w-full">
            <Navbar />
            {children}
          </div>
        </AuthProvider>
      </body>
    </html>
  );
}
