//app\layout.js
import Navbar from "@/app/components/Navbar";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
 
import { getServerSession } from "next-auth";
import SessionProvider from "@/utils/SessionProvider";
 
const inter = Inter({ subsets: ["latin"] });
 
export const metadata: Metadata = {
  title: "EarlyEdge",
  description: "Generated by create next app",
};
 
export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession();
  return (
    <html lang="en">
      <body className={`${inter.className} bg-gray-100`}> {/* Set a light background */}
        <SessionProvider session={session}>
          <div className="w-full"> {/* Removed container to ensure full-width layout */}
            <Navbar />
            {children} {/* Your landing page content will go here */}
          </div>
        </SessionProvider>
      </body>
    </html>
  );
}
